/* Univers du Café interactions. Edit product data directly in each HTML button. */
const rootPath=location.pathname.includes('/pages/')?'..':'.';
const footer=`<footer class="site-footer"><div><a class="brand" href="${rootPath}/index.html"><span class="brand-mark">☕</span><span>Univers<br><b>du Café</b></span></a><p>A coffee experience made for unhurried moments.</p></div><div><h4>Explore</h4><a href="${rootPath}/pages/menu.html">Menu</a><a href="${rootPath}/pages/about.html">About</a><a href="${rootPath}/index.html#gallery">Gallery</a><a href="${rootPath}/pages/contact.html">Contact</a></div><div><h4>Visit</h4><p>Casablanca, Morocco<br><small>Placeholder — easy to replace</small></p><p>+212 XX XX XX XX<br>hello@example.com</p></div><div><h4>Follow</h4><p class="socials"><a href="#">Instagram</a><a href="#">Facebook</a><a href="#">TikTok</a></p></div></footer><div class="copyright">© 2026 Univers du Café — Portfolio demo. All details may be customized.</div><aside class="cart-drawer" aria-label="Shopping cart"><div class="drawer-head"><h2>Your bag</h2><button class="close-cart" aria-label="Close cart">×</button></div><div class="cart-items"></div><div class="cart-total">Subtotal <b>$0.00</b></div><button class="button checkout">Demo checkout</button><p class="cart-note">Front-end demo — no payment is processed.</p></aside><div class="cart-overlay"></div><div class="lightbox" aria-hidden="true"><button class="lightbox-close" aria-label="Close image">×</button><img src="" alt="Gallery view"></div><button class="back-top" aria-label="Back to top">↑</button>`;
document.querySelectorAll('[data-footer]').forEach(el=>el.outerHTML=footer);
let cart=JSON.parse(localStorage.getItem('udc-cart')||'[]');
const money=n=>`$${n.toFixed(2)}`; const save=()=>localStorage.setItem('udc-cart',JSON.stringify(cart));
function renderCart(){const items=document.querySelector('.cart-items');if(!items)return;items.innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><img src="${x.image}" alt="${x.name}"><div><h4>${x.name}</h4><p>${money(x.price)}</p><div class="cart-qty"><button data-change="-" data-id="${x.id}">−</button><span>${x.qty}</span><button data-change="+" data-id="${x.id}">+</button></div></div><button class="remove-item" data-remove="${x.id}" aria-label="Remove ${x.name}">×</button></div>`).join(''):'<p class="demo-note">Your bag is waiting for something lovely.</p>';const total=cart.reduce((a,x)=>a+x.price*x.qty,0);document.querySelector('.cart-total b').textContent=money(total);document.querySelectorAll('.cart-count').forEach(x=>x.textContent=cart.reduce((a,x)=>a+x.qty,0));save()}
function add(button){const p={id:button.dataset.id,name:button.dataset.name,price:+button.dataset.price,image:new URL(button.dataset.image,location.href).href,qty:button.classList.contains('product-add')?qty:1};const found=cart.find(x=>x.id===p.id);found?found.qty+=p.qty:cart.push(p);renderCart();openCart()}
document.addEventListener('click',e=>{const addBtn=e.target.closest('.add-btn,.product-add');if(addBtn&&addBtn.tagName==='BUTTON')add(addBtn);if(e.target.matches('[data-change]')){const x=cart.find(i=>i.id===e.target.dataset.id);x.qty+=e.target.dataset.change==='+'?1:-1;if(x.qty<1)cart=cart.filter(i=>i!==x);renderCart()}if(e.target.matches('[data-remove]')){cart=cart.filter(i=>i.id!==e.target.dataset.remove);renderCart()}});
const drawer=()=>document.querySelector('.cart-drawer'), overlay=()=>document.querySelector('.cart-overlay');function openCart(){drawer()?.classList.add('open');overlay()?.classList.add('show')}function closeCart(){drawer()?.classList.remove('open');overlay()?.classList.remove('show')}document.addEventListener('click',e=>{if(e.target.closest('.cart-trigger'))openCart();if(e.target.closest('.close-cart')||e.target.matches('.cart-overlay'))closeCart();});renderCart();
document.querySelector('.nav-toggle')?.addEventListener('click',e=>{const n=document.querySelector('.main-nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.menu-card').forEach(card=>card.classList.toggle('hidden',btn.dataset.filter!=='all'&&card.dataset.category!==btn.dataset.filter))}));
document.querySelectorAll('.gallery-item').forEach(b=>b.addEventListener('click',()=>{const l=document.querySelector('.lightbox');l.querySelector('img').src=b.querySelector('img').src;l.classList.add('open');l.setAttribute('aria-hidden','false')}));document.addEventListener('click',e=>{if(e.target.matches('.lightbox,.lightbox-close')){const l=document.querySelector('.lightbox');l?.classList.remove('open');l?.setAttribute('aria-hidden','true')}});
const form=document.querySelector('.contact-form');form?.addEventListener('submit',e=>{e.preventDefault();const msg=form.querySelector('.form-message');if(!form.checkValidity()){msg.textContent='Please enter your name, a valid email, and a message.';form.reportValidity();return}msg.textContent='Thank you — this demo form has been validated locally.';form.reset()});
document.querySelectorAll('.size').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));let qty=1;document.querySelectorAll('[data-qty]').forEach(b=>b.addEventListener('click',()=>{qty=Math.max(1,qty+(b.dataset.qty==='+'?1:-1));b.parentElement.querySelector('span').textContent=qty}));
const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.13});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));const back=document.querySelector('.back-top');window.addEventListener('scroll',()=>{back?.classList.toggle('show',scrollY>500);document.querySelector('.site-header:not(.inner)')?.classList.toggle('scrolled',scrollY>50)});back?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
